title: Miłosz Wąsacz
description: Personal portfolio
baseurl: ""
url: https://miloszwasacz.github.io

theme: cvless

# site settings
taglong: Computer Science student<br />at University of Bristol
tagshort: Personal portfolio

# author settings
author:
    name: Miłosz Wąsacz
    email: wasacz.dev@gmail.com
photo: assets/files/profile_picture.png
joblines:
    - University of Bristol
    - Faculty of Science and Engineering
    - School of Computer Science
address: Bristol, United Kingdom
# phone: +1 234 567 890

# profile links
profile:
    github: https://github.com/miloszwasacz
    stackoverflow: https://stackoverflow.com/users/23104921/miloszwasacz
    # medium: https://medium.com/@username
    # facebook: https://www.facebook.com/username
    # x: https://x.com/username
    # mastodon: https://mastodon.social/@username
    # bluesky: https://bsky.app/profile/username.bsky.social
    # instagram: https://www.instagram.com/username
    linkedin: https://www.linkedin.com/in/miloszwasacz
    cv: true

# collections
collections:
    projects:
        output: true

# build settings
permalink: pretty
exclude:
    - LICENSE
    - README.md
    - Gemfile
    - Gemfile.lock
    - vendor/
    - docker-compose.yml

plugins:
    - jekyll-feed
    - jekyll-gist
    - jekyll-paginate-v2
    - jekyll-seo-tag
    - jekyll-sitemap

sass:
    sourcemap: never
